### ISSUE TITLE
Doesn't run in recent Meteor versions

### ISSUE THREAD

**Issue by devphc** [gadicc/meteor-rest-test#3]
![image](https://cloud.githubusercontent.com/assets/15830676/18700258/d1b821b6-8008-11e6-8fd7-a5a8f07b67f1.png)

**Comment by gadicc** [comment]
Hi @phc1212.  Regrettably this package is super old (I last worked on it 3 years ago) and I don't have any intention to upgrade it to work with the latest Meteor.  I'd happily accept a PR if someone else can do that though :)  Sorry I don't have better news.

**Comment by devphc** [comment]
Oh! That's too bad

**Comment by devphc** [comment]
leave
